/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    MyButton: typeof import('./src/components/MyButton/index.vue')['default']
    MyInput: typeof import('./src/components/MyInput/index.vue')['default']
  }
}
